/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_grass_applicationso_myJNI */

#ifndef _Included_com_example_grass_applicationso_myJNI
#define _Included_com_example_grass_applicationso_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_grass_applicationso_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_grass_applicationso_myJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
